### PR TITLE
Foolproof: Disable VAD if clip_timestamps is in use

### PR DESCRIPTION
**Pull request by Purfview**
Prevent silly things to happen.

### CODE REVIEW

**Comment by trungkienbkhn** [comment]
@Purfview , could you provide an example of the strange behavior if using both vad_filter and clip_timestamp ?

**Comment by Purfview** [comment]
> @Purfview , could you provide an example of the strange behavior if using both vad_filter and clip_timestamp ?

`clip_timestamps` is like custom/manual VAD and it runs after Silero VAD code. Them both running at same time doesn't make sense.

For example you want to transcribe only the second minute of audio and set`clip_timestamps="120,180"`, if VAD is enabled then audio can be different and the second minute wouldn't be at "120,180" anymore., transcription would happen at some unknown portion of audio.

**Comment by trungkienbkhn** [comment]
Okay. But I think you should add a comment or logging for this update logic code: vad_filter will be ignored if clip_timestamp is used.

**Comment by Purfview** [comment]
Comment added.

**Pull request merged**
