### PR TITLE
Add Pydantic typing

### PR DESCRIPTION
**Pull request by extrange**
Hi, we are using this library extensively at our company, and internally we have added type validation with Pydantic. If this is useful, I can update the documentation as well.

### CODE REVIEW

**Comment by MahmoudAshraf97** [comment]
Hello, I'm not well experienced with pydantic tbh, can you explain how this is useful or helps ease future maintainability? I know there is a lot of code duplication that this reduces but is there other benefits?

**Comment by extrange** [comment]
We have a use case where we need to serialize the output `tuple[Iterable[Segment], TranscriptionInfo]` into JSON, and then deserialize it back into a typed Python object/model.

Namedtuples do not natively allow nested deserialization. For example, using the following JSON:

```python
segments, info = model.transcribe(audio, word_timestamps=True)
out = [s_asdict() for s in segments]
print(json.dumps(out, indent=2))
```

```json5
[
  {
    "id": 1,
    "seek": 2490,
    "start": 0.0,
    "end": 6.0,
    "text": " Ladies and gentlemen, thank you for being here and for your written representations.",
    "tokens": [
      50364,
      //...
    ],
    "avg_logprob": -0.26516544380608725,
    "compression_ratio": 1.597883597883598,
    "no_speech_prob": 0.01361083984375,
    "words": null,
    "temperature": 0.0
  },
//...
]

```
If we try to convert this back to a `list[Segment]`, the `words` is not converted:

```python
from faster_whisper.transcribe import Segment
[Segment(**s) for s in parsed]
```
```python
Segment(
    id=1,
    seek=2490,
    start=0.0,
    end=4.62,
    text=" Ladies and gentlemen, thank you for being here and for your written representations.",
    tokens=[
        50364,
# ...
    ],
    avg_logprob=-0.26516544380608725,
    compression_ratio=1.597883597883598,
    no_speech_prob=0.01361083984375,
    words=[
        [0.0, 0.32, " Ladies", 0.310546875],
        [0.32, 0.54, " and", 0.89453125],
# ...
    ],
    temperature=0.0,
)

```

Currently, we are [recursing through the `Segment` and `TranscriptionInfo` objects](https://github.com/extrange/transcription-benchmarks/blob/705a097a493f6c32086fa434b8f326cfee099e8b/src/transcription_benchmarks/inference/systran_faster_whisper_large_v2/inference.py#L333-L357) to convert them to Pydantic models (which natively allow nested deserialization), but it would be nice if the library supported this out of the box.

**Comment by MahmoudAshraf97** [comment]
I see, but why not use `dataclass`? it supports recursive serialization too and will not add an extra dependency or change much in the code

**Comment by extrange** [comment]
I think dataclasses are not serializable to JSON, at least not without [another library](https://github.com/lidatong/dataclasses-json):

```python
import json
from dataclasses import dataclass


@dataclass
class Foo:
    x: str


foo = Foo(x="bar")
json.dumps(foo)

# TypeError: Object of type Foo is not JSON serializable
```

**Comment by extrange** [comment]
Closed in favour of #1105

**Pull request closed without merging**
